### ISSUE TITLE
NoDelay pass variables

### ISSUE THREAD

**Issue by ProtomakerSprint** [M-tech-Creations/NoDelay#1]
NoDelay pass variables Issue

#include <NoDelay.h> 

 ...

void feeddropPulses();  // Must declare function before noDelay, function can not take arguments

noDelay timedFeeddropPulses(1000 * 10, feeddropPulses); // Creats a noDelay varible set to 10s, will call feeddropPulses function

....

loop

timedFeeddropPulses.update();

....

void feeddropPulses(){
  // long dropPulses, int ledGreenfeedLiquid) { // want these passed variables Issue
//}

Thanking You

My code was working but, does not any more.

**Comment by M-tech-Creations** [comment]
I'm guessing the line you are having problems with is this one: long dropPulses, int ledGreenfeedLiquid?

The way NoDelay is written, you are not able to pass variables directly to the function NoDelay is calling, the way around that is to use global variables. Without seeing the whole code its hard to see what it is thats having the problem.

**Comment by M-tech-Creations** [comment]
A work around would be to use an if statement check rather then a function update. So,

```
noDelay timedFeeddropPulses(1000 * 10);

loop(){
    if (timedFeeddropPulses.update()) {
        feeddropPulses(dropPulses,ledGreenfeedLiquid);
    }
}
```

This gets around the limit of not being able to pass information to a function being called by NoDelay with only a few lines of code.
