### ISSUE TITLE
How to stop a delay?

### ISSUE THREAD

**Issue by danilolima** [M-tech-Creations/NoDelay#2]
Is there a way to stop the delay of running forever?

**Comment by M-tech-Creations** [comment]
As of right now there is no Stop function to keep functions from being called or return values of True when .update() is called. This wasn't a use case I thought of when creating this library. If this is functionality you are looking for I could add it.

**Comment by M-tech-Creations** [comment]
Otherwise if you want code to keep executing without a delay, you can pass the .setdelay() function a zero which would bypass any delay.

**Comment by M-tech-Creations** [comment]
@danilolima I have pushed version 2.1.0 in it there is now a stop function. You can use it so keep NoDelay from running code. To start again just use the start function, which will also restart the delay clock. If you need to have a NoDelay object start off being stoped you can add false to the end of the setup.

noDelay somethingTodelay(1000,false);
or
noDelay somethingTodelay(1000, aFunction, false);

Feel free to test and see if it works for you

**Comment by danilolima** [comment]
Thanks for the stop function @M-tech-Creations!
Love this lib.
