### ISSUE TITLE
Update method should return false if isenabled == false

### ISSUE THREAD

**Issue by eAvio** [M-tech-Creations/NoDelay#4]
We are using nodelay method on very rare occasions to trigger one function after few seconds. But "update" method is still called in each loop although "stop()" was called.

This somehow interfere with mqtt library causing some delays in receiving messages.

What I suggest is to add check at the top of update() method:

```
bool noDelay::update()
{
	if(!isenabled)
	{
		return false;
	}

```

**Comment by M-tech-Creations** [comment]
I implemented the proposed change and can be found in release 2.1.1 which should be be in the Arduino Library Manager in a few hours, or just downloaded now. Please let me know if your issue has been resolved. Thanks for using my library!
