### ISSUE TITLE
enabled flag

### ISSUE THREAD

**Issue by YouCanNotBeSerious** [M-tech-Creations/NoDelay#8]
I use this lib quite a lot - thank you.  Once thing that has come up a couple of times now:

I want to disable a timer, AND check elsewhere if ti has been disabled.

Could there be a timerName.enabled() that returns TRUE or FALSE added?

**Comment by M-tech-Creations** [comment]
That is not a bad suggestion, nor would it be difficult to implement. Once I get to my computer I'll look into adding this.

**Comment by YouCanNotBeSerious** [comment]
Great!  At the moment I use a separate “enabled” variable to do this, it’s not a big deal but would seem more elegant. 

If it helps, the use case is that dependant on user input, a noDelay object gets a .start or .stop. Elsewhere I display the status of the related task, and can’t just call .enabled for those delays.

**Comment by M-tech-Creations** [comment]
Hi have released version 2.2.0 which now has an enabled function. It should show up in the library manager soon or you can download it from the releases page to try. Let me know if it works as intended for you.

-Mario

**Comment by YouCanNotBeSerious** [comment]
Hi - 

OK so cutting to the chase - all works fine, I'm very appreciative of the added feature and I'm sure others will be :-)

In more detail if it helps:

- I updated through the library manager, v2.2.0 appears fine as an update
- My code already uses .stop() and .start() but not the deprecated .fupdate and not set .setdelay()
- New version works fine with my existing code
- Added the use of .enabled() instead of tracking this state through my own bool variable, works great. More elegant, more readable.

Thanks!

**Comment by M-tech-Creations** [comment]
Wonderful to hear it's working and thank you for the feedback. I'm sure others are going to benefit from this. Happy coding!

-Mario
